theme: minima

baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://ses-life.github.io" # the base hostname & protocol for your site
permalink: /:title

title: Дезинсекция, дератизация, дезинфекция, дезодорация - СЭС-life

description: Санитарно-эпидемиологическая служба. Уничтожение насекомых, грызунов, неприятных запахов с гарантией.

email: "sherbakovrf@gmail.com" # info@ses-life.ru
tel: "+7-938-473-1791" # +7-918-299-9009

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  ignore:
    envs: [local]

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      sitemap: true

sass:
  style: compressed

plugins:
  - jekyll-sitemap
